<?php

/**
 * @file
 * Code for the download_count module.
 */

use Drupal\node\NodeInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function download_count_node_view_alter(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  if($node->getType() == 'resource' AND $display->getMode() == 'full') {
    $build['#attached']['library'][] = 'download_count/main';

    $build['#attached']['drupalSettings']['download_count'] = [
      'nid' => $node->id(),
      'url' => '/download_count/add/'.$node->id()
    ];
  }
}
