<?php

/**
 * @file
 * Code for the twitter_last module.
 */

function twitter_last_theme($existing, $type, $theme, $path) {
  return array(
    'tweet_display' => array(
      'variables' => array('text' => array(), 'created_at' => NULL, 'user' => NULL),
      'path' => drupal_get_path('module', 'twitter_last') . '/templates',
      'template' => 'tweet'
    ),
    'tweets_list' => array(
      'variables' => array('tweets' => array(), 'attributes' => array(), 'more_link_display' => 0),
      'path' => drupal_get_path('module', 'twitter_last') . '/templates',
      'template' => 'tweets-list'
    ),
  );
}