<?php

/**
 * @file
 * Contains abt_videoembed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function abt_videoembed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.abt_videoembed':
      $output = '';
      $output .= '<h3>' . t('CKEditor ABT VideoEmbed') . '</h3>';
      $output .= '<p>' . t('The module adds a CKEditor video embed button to the editor toolbar and a link to its context menu (only available if you select an existing videoembed tag in the editor content).') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the icon into the active toolbar.', array(':text-formats' => \Drupal::url('filter.admin_overview'))) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}
