<?php

function abt_common_theme($existing, $type, $theme, $path) {
  return [
    'datetime_summary' => [
      'variables' => [
        'combined' => FALSE,
        'month' => NULL,
        'dates' => NULL,
        'start_month' => NULL,
        'start_date' => NULL,
        'end_month' => NULL,
        'end_date' => NULL,
        'end_year' => NULL,
        'start_year' => NULL,
        'year' => NULL,
      ],
    ],
  ];
}